from setuptools import setup

setup(
    name='QuadCamView',
    version='0.0.1',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.importlib', 'venv.Lib.collections',
              'venv.Lib.site-packages.cv2', 'venv.Lib.site-packages.cv2.data', 'venv.Lib.site-packages.jfu',
              'venv.Lib.site-packages.jfu.templatetags', 'venv.Lib.site-packages.PIL', 'venv.Lib.site-packages.pip',
              'venv.Lib.site-packages.pip._vendor', 'venv.Lib.site-packages.pip._vendor.idna',
              'venv.Lib.site-packages.pip._vendor.pep517', 'venv.Lib.site-packages.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip._vendor.certifi', 'venv.Lib.site-packages.pip._vendor.chardet',
              'venv.Lib.site-packages.pip._vendor.chardet.cli', 'venv.Lib.site-packages.pip._vendor.distlib',
              'venv.Lib.site-packages.pip._vendor.distlib._backport', 'venv.Lib.site-packages.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip._vendor.urllib3', 'venv.Lib.site-packages.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip._vendor.progress', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.packaging', 'venv.Lib.site-packages.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip._vendor.webencodings', 'venv.Lib.site-packages.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip._internal', 'venv.Lib.site-packages.pip._internal.cli',
              'venv.Lib.site-packages.pip._internal.req', 'venv.Lib.site-packages.pip._internal.vcs',
              'venv.Lib.site-packages.pip._internal.utils', 'venv.Lib.site-packages.pip._internal.models',
              'venv.Lib.site-packages.pip._internal.commands', 'venv.Lib.site-packages.pip._internal.operations',
              'venv.Lib.site-packages.dill', 'venv.Lib.site-packages.dill.tests', 'venv.Lib.site-packages.idna',
              'venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.sorl', 'venv.Lib.site-packages.sorl.thumbnail',
              'venv.Lib.site-packages.sorl.thumbnail.conf', 'venv.Lib.site-packages.sorl.thumbnail.admin',
              'venv.Lib.site-packages.sorl.thumbnail.engines', 'venv.Lib.site-packages.sorl.thumbnail.kvstores',
              'venv.Lib.site-packages.sorl.thumbnail.management',
              'venv.Lib.site-packages.sorl.thumbnail.management.commands',
              'venv.Lib.site-packages.sorl.thumbnail.migrations', 'venv.Lib.site-packages.sorl.thumbnail.templatetags',
              'venv.Lib.site-packages.AnyQt', 'venv.Lib.site-packages.AnyQt._backport', 'venv.Lib.site-packages.numpy',
              'venv.Lib.site-packages.numpy.ma', 'venv.Lib.site-packages.numpy.ma.tests',
              'venv.Lib.site-packages.numpy.doc', 'venv.Lib.site-packages.numpy.fft',
              'venv.Lib.site-packages.numpy.fft.tests', 'venv.Lib.site-packages.numpy.lib',
              'venv.Lib.site-packages.numpy.lib.tests', 'venv.Lib.site-packages.numpy.core',
              'venv.Lib.site-packages.numpy.core.tests', 'venv.Lib.site-packages.numpy.f2py',
              'venv.Lib.site-packages.numpy.f2py.tests', 'venv.Lib.site-packages.numpy.tests',
              'venv.Lib.site-packages.numpy.compat', 'venv.Lib.site-packages.numpy.compat.tests',
              'venv.Lib.site-packages.numpy.linalg', 'venv.Lib.site-packages.numpy.linalg.tests',
              'venv.Lib.site-packages.numpy.random', 'venv.Lib.site-packages.numpy.random.tests',
              'venv.Lib.site-packages.numpy.testing', 'venv.Lib.site-packages.numpy.testing.tests',
              'venv.Lib.site-packages.numpy.testing._private', 'venv.Lib.site-packages.numpy.distutils',
              'venv.Lib.site-packages.numpy.distutils.tests', 'venv.Lib.site-packages.numpy.distutils.command',
              'venv.Lib.site-packages.numpy.distutils.fcompiler', 'venv.Lib.site-packages.numpy.matrixlib',
              'venv.Lib.site-packages.numpy.matrixlib.tests', 'venv.Lib.site-packages.numpy.polynomial',
              'venv.Lib.site-packages.numpy.polynomial.tests', 'venv.Lib.site-packages.PyQt5',
              'venv.Lib.site-packages.PyQt5.uic', 'venv.Lib.site-packages.PyQt5.uic.Loader',
              'venv.Lib.site-packages.PyQt5.uic.port_v2', 'venv.Lib.site-packages.PyQt5.uic.port_v3',
              'venv.Lib.site-packages.PyQt5.uic.Compiler', 'venv.Lib.site-packages.wheel',
              'venv.Lib.site-packages.wheel.cli', 'venv.Lib.site-packages.django', 'venv.Lib.site-packages.django.db',
              'venv.Lib.site-packages.django.db.models', 'venv.Lib.site-packages.django.db.models.sql',
              'venv.Lib.site-packages.django.db.models.fields', 'venv.Lib.site-packages.django.db.models.functions',
              'venv.Lib.site-packages.django.db.backends', 'venv.Lib.site-packages.django.db.backends.base',
              'venv.Lib.site-packages.django.db.backends.dummy', 'venv.Lib.site-packages.django.db.backends.mysql',
              'venv.Lib.site-packages.django.db.backends.oracle', 'venv.Lib.site-packages.django.db.backends.sqlite3',
              'venv.Lib.site-packages.django.db.backends.postgresql',
              'venv.Lib.site-packages.django.db.backends.postgresql_psycopg2',
              'venv.Lib.site-packages.django.db.migrations', 'venv.Lib.site-packages.django.db.migrations.operations',
              'venv.Lib.site-packages.django.apps', 'venv.Lib.site-packages.django.conf',
              'venv.Lib.site-packages.django.conf.urls', 'venv.Lib.site-packages.django.conf.locale',
              'venv.Lib.site-packages.django.conf.locale.ar', 'venv.Lib.site-packages.django.conf.locale.az',
              'venv.Lib.site-packages.django.conf.locale.bg', 'venv.Lib.site-packages.django.conf.locale.bn',
              'venv.Lib.site-packages.django.conf.locale.bs', 'venv.Lib.site-packages.django.conf.locale.ca',
              'venv.Lib.site-packages.django.conf.locale.cs', 'venv.Lib.site-packages.django.conf.locale.cy',
              'venv.Lib.site-packages.django.conf.locale.da', 'venv.Lib.site-packages.django.conf.locale.de',
              'venv.Lib.site-packages.django.conf.locale.el', 'venv.Lib.site-packages.django.conf.locale.en',
              'venv.Lib.site-packages.django.conf.locale.eo', 'venv.Lib.site-packages.django.conf.locale.es',
              'venv.Lib.site-packages.django.conf.locale.et', 'venv.Lib.site-packages.django.conf.locale.eu',
              'venv.Lib.site-packages.django.conf.locale.fa', 'venv.Lib.site-packages.django.conf.locale.fi',
              'venv.Lib.site-packages.django.conf.locale.fr', 'venv.Lib.site-packages.django.conf.locale.fy',
              'venv.Lib.site-packages.django.conf.locale.ga', 'venv.Lib.site-packages.django.conf.locale.gd',
              'venv.Lib.site-packages.django.conf.locale.gl', 'venv.Lib.site-packages.django.conf.locale.he',
              'venv.Lib.site-packages.django.conf.locale.hi', 'venv.Lib.site-packages.django.conf.locale.hr',
              'venv.Lib.site-packages.django.conf.locale.hu', 'venv.Lib.site-packages.django.conf.locale.id',
              'venv.Lib.site-packages.django.conf.locale.is', 'venv.Lib.site-packages.django.conf.locale.it',
              'venv.Lib.site-packages.django.conf.locale.ja', 'venv.Lib.site-packages.django.conf.locale.ka',
              'venv.Lib.site-packages.django.conf.locale.km', 'venv.Lib.site-packages.django.conf.locale.kn',
              'venv.Lib.site-packages.django.conf.locale.ko', 'venv.Lib.site-packages.django.conf.locale.lt',
              'venv.Lib.site-packages.django.conf.locale.lv', 'venv.Lib.site-packages.django.conf.locale.mk',
              'venv.Lib.site-packages.django.conf.locale.ml', 'venv.Lib.site-packages.django.conf.locale.mn',
              'venv.Lib.site-packages.django.conf.locale.nb', 'venv.Lib.site-packages.django.conf.locale.nl',
              'venv.Lib.site-packages.django.conf.locale.nn', 'venv.Lib.site-packages.django.conf.locale.pl',
              'venv.Lib.site-packages.django.conf.locale.pt', 'venv.Lib.site-packages.django.conf.locale.ro',
              'venv.Lib.site-packages.django.conf.locale.ru', 'venv.Lib.site-packages.django.conf.locale.sk',
              'venv.Lib.site-packages.django.conf.locale.sl', 'venv.Lib.site-packages.django.conf.locale.sq',
              'venv.Lib.site-packages.django.conf.locale.sr', 'venv.Lib.site-packages.django.conf.locale.sv',
              'venv.Lib.site-packages.django.conf.locale.ta', 'venv.Lib.site-packages.django.conf.locale.te',
              'venv.Lib.site-packages.django.conf.locale.th', 'venv.Lib.site-packages.django.conf.locale.tr',
              'venv.Lib.site-packages.django.conf.locale.uk', 'venv.Lib.site-packages.django.conf.locale.vi',
              'venv.Lib.site-packages.django.conf.locale.de_CH', 'venv.Lib.site-packages.django.conf.locale.en_AU',
              'venv.Lib.site-packages.django.conf.locale.en_GB', 'venv.Lib.site-packages.django.conf.locale.es_AR',
              'venv.Lib.site-packages.django.conf.locale.es_CO', 'venv.Lib.site-packages.django.conf.locale.es_MX',
              'venv.Lib.site-packages.django.conf.locale.es_NI', 'venv.Lib.site-packages.django.conf.locale.es_PR',
              'venv.Lib.site-packages.django.conf.locale.pt_BR', 'venv.Lib.site-packages.django.conf.locale.sr_Latn',
              'venv.Lib.site-packages.django.conf.locale.zh_Hans', 'venv.Lib.site-packages.django.conf.locale.zh_Hant',
              'venv.Lib.site-packages.django.core', 'venv.Lib.site-packages.django.core.mail',
              'venv.Lib.site-packages.django.core.mail.backends', 'venv.Lib.site-packages.django.core.cache',
              'venv.Lib.site-packages.django.core.cache.backends', 'venv.Lib.site-packages.django.core.files',
              'venv.Lib.site-packages.django.core.checks', 'venv.Lib.site-packages.django.core.checks.security',
              'venv.Lib.site-packages.django.core.checks.compatibility', 'venv.Lib.site-packages.django.core.servers',
              'venv.Lib.site-packages.django.core.handlers', 'venv.Lib.site-packages.django.core.management',
              'venv.Lib.site-packages.django.core.serializers', 'venv.Lib.site-packages.django.http',
              'venv.Lib.site-packages.django.test', 'venv.Lib.site-packages.django.urls',
              'venv.Lib.site-packages.django.forms', 'venv.Lib.site-packages.django.utils',
              'venv.Lib.site-packages.django.utils.translation', 'venv.Lib.site-packages.django.views',
              'venv.Lib.site-packages.django.views.generic', 'venv.Lib.site-packages.django.views.decorators',
              'venv.Lib.site-packages.django.contrib', 'venv.Lib.site-packages.django.contrib.gis',
              'venv.Lib.site-packages.django.contrib.gis.db', 'venv.Lib.site-packages.django.contrib.gis.db.models',
              'venv.Lib.site-packages.django.contrib.gis.db.models.sql',
              'venv.Lib.site-packages.django.contrib.gis.db.backends',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.base',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.mysql',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.oracle',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.postgis',
              'venv.Lib.site-packages.django.contrib.gis.db.backends.spatialite',
              'venv.Lib.site-packages.django.contrib.gis.gdal', 'venv.Lib.site-packages.django.contrib.gis.gdal.raster',
              'venv.Lib.site-packages.django.contrib.gis.gdal.prototypes',
              'venv.Lib.site-packages.django.contrib.gis.geos',
              'venv.Lib.site-packages.django.contrib.gis.geos.prototypes',
              'venv.Lib.site-packages.django.contrib.gis.admin', 'venv.Lib.site-packages.django.contrib.gis.forms',
              'venv.Lib.site-packages.django.contrib.gis.utils', 'venv.Lib.site-packages.django.contrib.gis.geoip2',
              'venv.Lib.site-packages.django.contrib.gis.sitemaps',
              'venv.Lib.site-packages.django.contrib.gis.serializers', 'venv.Lib.site-packages.django.contrib.auth',
              'venv.Lib.site-packages.django.contrib.auth.handlers',
              'venv.Lib.site-packages.django.contrib.auth.management',
              'venv.Lib.site-packages.django.contrib.auth.migrations', 'venv.Lib.site-packages.django.contrib.admin',
              'venv.Lib.site-packages.django.contrib.admin.views',
              'venv.Lib.site-packages.django.contrib.admin.migrations',
              'venv.Lib.site-packages.django.contrib.admin.templatetags', 'venv.Lib.site-packages.django.contrib.sites',
              'venv.Lib.site-packages.django.contrib.sites.migrations',
              'venv.Lib.site-packages.django.contrib.humanize',
              'venv.Lib.site-packages.django.contrib.humanize.templatetags',
              'venv.Lib.site-packages.django.contrib.messages',
              'venv.Lib.site-packages.django.contrib.messages.storage',
              'venv.Lib.site-packages.django.contrib.postgres', 'venv.Lib.site-packages.django.contrib.postgres.forms',
              'venv.Lib.site-packages.django.contrib.postgres.fields',
              'venv.Lib.site-packages.django.contrib.postgres.aggregates',
              'venv.Lib.site-packages.django.contrib.sessions',
              'venv.Lib.site-packages.django.contrib.sessions.backends',
              'venv.Lib.site-packages.django.contrib.sessions.migrations',
              'venv.Lib.site-packages.django.contrib.sitemaps', 'venv.Lib.site-packages.django.contrib.admindocs',
              'venv.Lib.site-packages.django.contrib.flatpages',
              'venv.Lib.site-packages.django.contrib.flatpages.migrations',
              'venv.Lib.site-packages.django.contrib.flatpages.templatetags',
              'venv.Lib.site-packages.django.contrib.redirects',
              'venv.Lib.site-packages.django.contrib.redirects.migrations',
              'venv.Lib.site-packages.django.contrib.staticfiles',
              'venv.Lib.site-packages.django.contrib.staticfiles.templatetags',
              'venv.Lib.site-packages.django.contrib.syndication', 'venv.Lib.site-packages.django.contrib.contenttypes',
              'venv.Lib.site-packages.django.contrib.contenttypes.management',
              'venv.Lib.site-packages.django.contrib.contenttypes.migrations', 'venv.Lib.site-packages.django.dispatch',
              'venv.Lib.site-packages.django.template', 'venv.Lib.site-packages.django.template.loaders',
              'venv.Lib.site-packages.django.template.backends', 'venv.Lib.site-packages.django.middleware',
              'venv.Lib.site-packages.django.templatetags', 'venv.Lib.site-packages.OpenGL',
              'venv.Lib.site-packages.OpenGL.GL', 'venv.Lib.site-packages.OpenGL.GL.FJ',
              'venv.Lib.site-packages.OpenGL.GL.HP', 'venv.Lib.site-packages.OpenGL.GL.NV',
              'venv.Lib.site-packages.OpenGL.GL.S3', 'venv.Lib.site-packages.OpenGL.GL.AMD',
              'venv.Lib.site-packages.OpenGL.GL.ARB', 'venv.Lib.site-packages.OpenGL.GL.ARM',
              'venv.Lib.site-packages.OpenGL.GL.ATI', 'venv.Lib.site-packages.OpenGL.GL.DFX',
              'venv.Lib.site-packages.OpenGL.GL.DMP', 'venv.Lib.site-packages.OpenGL.GL.EXT',
              'venv.Lib.site-packages.OpenGL.GL.IBM', 'venv.Lib.site-packages.OpenGL.GL.IMG',
              'venv.Lib.site-packages.OpenGL.GL.KHR', 'venv.Lib.site-packages.OpenGL.GL.NVX',
              'venv.Lib.site-packages.OpenGL.GL.OES', 'venv.Lib.site-packages.OpenGL.GL.OML',
              'venv.Lib.site-packages.OpenGL.GL.PGI', 'venv.Lib.site-packages.OpenGL.GL.SGI',
              'venv.Lib.site-packages.OpenGL.GL.SUN', 'venv.Lib.site-packages.OpenGL.GL.VIV',
              'venv.Lib.site-packages.OpenGL.GL.WIN', 'venv.Lib.site-packages.OpenGL.GL.INGR',
              'venv.Lib.site-packages.OpenGL.GL.MESA', 'venv.Lib.site-packages.OpenGL.GL.QCOM',
              'venv.Lib.site-packages.OpenGL.GL.REND', 'venv.Lib.site-packages.OpenGL.GL.SGIS',
              'venv.Lib.site-packages.OpenGL.GL.SGIX', 'venv.Lib.site-packages.OpenGL.GL.SUNX',
              'venv.Lib.site-packages.OpenGL.GL.ANGLE', 'venv.Lib.site-packages.OpenGL.GL.APPLE',
              'venv.Lib.site-packages.OpenGL.GL.INTEL', 'venv.Lib.site-packages.OpenGL.GL.MESAX',
              'venv.Lib.site-packages.OpenGL.GL.GREMEDY', 'venv.Lib.site-packages.OpenGL.GL.VERSION',
              'venv.Lib.site-packages.OpenGL.Tk', 'venv.Lib.site-packages.OpenGL.AGL',
              'venv.Lib.site-packages.OpenGL.EGL', 'venv.Lib.site-packages.OpenGL.EGL.HI',
              'venv.Lib.site-packages.OpenGL.EGL.NV', 'venv.Lib.site-packages.OpenGL.EGL.ARM',
              'venv.Lib.site-packages.OpenGL.EGL.EXT', 'venv.Lib.site-packages.OpenGL.EGL.IMG',
              'venv.Lib.site-packages.OpenGL.EGL.KHR', 'venv.Lib.site-packages.OpenGL.EGL.NOK',
              'venv.Lib.site-packages.OpenGL.EGL.MESA', 'venv.Lib.site-packages.OpenGL.EGL.ANGLE',
              'venv.Lib.site-packages.OpenGL.EGL.ANDROID', 'venv.Lib.site-packages.OpenGL.EGL.VERSION',
              'venv.Lib.site-packages.OpenGL.GLE', 'venv.Lib.site-packages.OpenGL.GLU',
              'venv.Lib.site-packages.OpenGL.GLU.EXT', 'venv.Lib.site-packages.OpenGL.GLX',
              'venv.Lib.site-packages.OpenGL.GLX.NV', 'venv.Lib.site-packages.OpenGL.GLX.AMD',
              'venv.Lib.site-packages.OpenGL.GLX.ARB', 'venv.Lib.site-packages.OpenGL.GLX.DFX',
              'venv.Lib.site-packages.OpenGL.GLX.EXT', 'venv.Lib.site-packages.OpenGL.GLX.OML',
              'venv.Lib.site-packages.OpenGL.GLX.SGI', 'venv.Lib.site-packages.OpenGL.GLX.SUN',
              'venv.Lib.site-packages.OpenGL.GLX.MESA', 'venv.Lib.site-packages.OpenGL.GLX.SGIS',
              'venv.Lib.site-packages.OpenGL.GLX.SGIX', 'venv.Lib.site-packages.OpenGL.GLX.INTEL',
              'venv.Lib.site-packages.OpenGL.GLX.VERSION', 'venv.Lib.site-packages.OpenGL.raw',
              'venv.Lib.site-packages.OpenGL.raw.GL', 'venv.Lib.site-packages.OpenGL.raw.GL.FJ',
              'venv.Lib.site-packages.OpenGL.raw.GL.HP', 'venv.Lib.site-packages.OpenGL.raw.GL.NV',
              'venv.Lib.site-packages.OpenGL.raw.GL.S3', 'venv.Lib.site-packages.OpenGL.raw.GL.AMD',
              'venv.Lib.site-packages.OpenGL.raw.GL.ARB', 'venv.Lib.site-packages.OpenGL.raw.GL.ARM',
              'venv.Lib.site-packages.OpenGL.raw.GL.ATI', 'venv.Lib.site-packages.OpenGL.raw.GL.DFX',
              'venv.Lib.site-packages.OpenGL.raw.GL.DMP', 'venv.Lib.site-packages.OpenGL.raw.GL.EXT',
              'venv.Lib.site-packages.OpenGL.raw.GL.IBM', 'venv.Lib.site-packages.OpenGL.raw.GL.IMG',
              'venv.Lib.site-packages.OpenGL.raw.GL.KHR', 'venv.Lib.site-packages.OpenGL.raw.GL.NVX',
              'venv.Lib.site-packages.OpenGL.raw.GL.OES', 'venv.Lib.site-packages.OpenGL.raw.GL.OML',
              'venv.Lib.site-packages.OpenGL.raw.GL.PGI', 'venv.Lib.site-packages.OpenGL.raw.GL.SGI',
              'venv.Lib.site-packages.OpenGL.raw.GL.SUN', 'venv.Lib.site-packages.OpenGL.raw.GL.VIV',
              'venv.Lib.site-packages.OpenGL.raw.GL.WIN', 'venv.Lib.site-packages.OpenGL.raw.GL.INGR',
              'venv.Lib.site-packages.OpenGL.raw.GL.MESA', 'venv.Lib.site-packages.OpenGL.raw.GL.QCOM',
              'venv.Lib.site-packages.OpenGL.raw.GL.REND', 'venv.Lib.site-packages.OpenGL.raw.GL.SGIS',
              'venv.Lib.site-packages.OpenGL.raw.GL.SGIX', 'venv.Lib.site-packages.OpenGL.raw.GL.SUNX',
              'venv.Lib.site-packages.OpenGL.raw.GL.ANGLE', 'venv.Lib.site-packages.OpenGL.raw.GL.APPLE',
              'venv.Lib.site-packages.OpenGL.raw.GL.INTEL', 'venv.Lib.site-packages.OpenGL.raw.GL.MESAX',
              'venv.Lib.site-packages.OpenGL.raw.GL.GREMEDY', 'venv.Lib.site-packages.OpenGL.raw.GL.VERSION',
              'venv.Lib.site-packages.OpenGL.raw.EGL', 'venv.Lib.site-packages.OpenGL.raw.EGL.HI',
              'venv.Lib.site-packages.OpenGL.raw.EGL.NV', 'venv.Lib.site-packages.OpenGL.raw.EGL.ARM',
              'venv.Lib.site-packages.OpenGL.raw.EGL.EXT', 'venv.Lib.site-packages.OpenGL.raw.EGL.IMG',
              'venv.Lib.site-packages.OpenGL.raw.EGL.KHR', 'venv.Lib.site-packages.OpenGL.raw.EGL.NOK',
              'venv.Lib.site-packages.OpenGL.raw.EGL.MESA', 'venv.Lib.site-packages.OpenGL.raw.EGL.ANGLE',
              'venv.Lib.site-packages.OpenGL.raw.EGL.ANDROID', 'venv.Lib.site-packages.OpenGL.raw.EGL.VERSION',
              'venv.Lib.site-packages.OpenGL.raw.GLE', 'venv.Lib.site-packages.OpenGL.raw.GLU',
              'venv.Lib.site-packages.OpenGL.raw.GLX', 'venv.Lib.site-packages.OpenGL.raw.GLX.NV',
              'venv.Lib.site-packages.OpenGL.raw.GLX.AMD', 'venv.Lib.site-packages.OpenGL.raw.GLX.ARB',
              'venv.Lib.site-packages.OpenGL.raw.GLX.DFX', 'venv.Lib.site-packages.OpenGL.raw.GLX.EXT',
              'venv.Lib.site-packages.OpenGL.raw.GLX.OML', 'venv.Lib.site-packages.OpenGL.raw.GLX.SGI',
              'venv.Lib.site-packages.OpenGL.raw.GLX.SUN', 'venv.Lib.site-packages.OpenGL.raw.GLX.MESA',
              'venv.Lib.site-packages.OpenGL.raw.GLX.SGIS', 'venv.Lib.site-packages.OpenGL.raw.GLX.SGIX',
              'venv.Lib.site-packages.OpenGL.raw.GLX.INTEL', 'venv.Lib.site-packages.OpenGL.raw.GLX.VERSION',
              'venv.Lib.site-packages.OpenGL.raw.WGL', 'venv.Lib.site-packages.OpenGL.raw.WGL.DL',
              'venv.Lib.site-packages.OpenGL.raw.WGL.NV', 'venv.Lib.site-packages.OpenGL.raw.WGL.AMD',
              'venv.Lib.site-packages.OpenGL.raw.WGL.ARB', 'venv.Lib.site-packages.OpenGL.raw.WGL.ATI',
              'venv.Lib.site-packages.OpenGL.raw.WGL.DFX', 'venv.Lib.site-packages.OpenGL.raw.WGL.EXT',
              'venv.Lib.site-packages.OpenGL.raw.WGL.I3D', 'venv.Lib.site-packages.OpenGL.raw.WGL.OML',
              'venv.Lib.site-packages.OpenGL.raw.WGL.VERSION', 'venv.Lib.site-packages.OpenGL.raw.GLUT',
              'venv.Lib.site-packages.OpenGL.raw.GLES1', 'venv.Lib.site-packages.OpenGL.raw.GLES1.NV',
              'venv.Lib.site-packages.OpenGL.raw.GLES1.AMD', 'venv.Lib.site-packages.OpenGL.raw.GLES1.ARM',
              'venv.Lib.site-packages.OpenGL.raw.GLES1.EXT', 'venv.Lib.site-packages.OpenGL.raw.GLES1.IMG',
              'venv.Lib.site-packages.OpenGL.raw.GLES1.OES', 'venv.Lib.site-packages.OpenGL.raw.GLES1.QCOM',
              'venv.Lib.site-packages.OpenGL.raw.GLES1.APPLE', 'venv.Lib.site-packages.OpenGL.raw.GLES1.VERSION',
              'venv.Lib.site-packages.OpenGL.raw.GLES2', 'venv.Lib.site-packages.OpenGL.raw.GLES2.FJ',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.NV', 'venv.Lib.site-packages.OpenGL.raw.GLES2.AMD',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.ARM', 'venv.Lib.site-packages.OpenGL.raw.GLES2.DMP',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.EXT', 'venv.Lib.site-packages.OpenGL.raw.GLES2.IMG',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.KHR', 'venv.Lib.site-packages.OpenGL.raw.GLES2.OES',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.VIV', 'venv.Lib.site-packages.OpenGL.raw.GLES2.QCOM',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.ANGLE', 'venv.Lib.site-packages.OpenGL.raw.GLES2.APPLE',
              'venv.Lib.site-packages.OpenGL.raw.GLES2.INTEL', 'venv.Lib.site-packages.OpenGL.raw.GLES2.VERSION',
              'venv.Lib.site-packages.OpenGL.raw.GLES3', 'venv.Lib.site-packages.OpenGL.raw.GLES3.VERSION',
              'venv.Lib.site-packages.OpenGL.raw.osmesa', 'venv.Lib.site-packages.OpenGL.WGL',
              'venv.Lib.site-packages.OpenGL.WGL.DL', 'venv.Lib.site-packages.OpenGL.WGL.NV',
              'venv.Lib.site-packages.OpenGL.WGL.AMD', 'venv.Lib.site-packages.OpenGL.WGL.ARB',
              'venv.Lib.site-packages.OpenGL.WGL.ATI', 'venv.Lib.site-packages.OpenGL.WGL.DFX',
              'venv.Lib.site-packages.OpenGL.WGL.EXT', 'venv.Lib.site-packages.OpenGL.WGL.I3D',
              'venv.Lib.site-packages.OpenGL.WGL.OML', 'venv.Lib.site-packages.OpenGL.WGL.VERSION',
              'venv.Lib.site-packages.OpenGL.GLUT', 'venv.Lib.site-packages.OpenGL.GLES1',
              'venv.Lib.site-packages.OpenGL.GLES1.NV', 'venv.Lib.site-packages.OpenGL.GLES1.AMD',
              'venv.Lib.site-packages.OpenGL.GLES1.ARM', 'venv.Lib.site-packages.OpenGL.GLES1.EXT',
              'venv.Lib.site-packages.OpenGL.GLES1.IMG', 'venv.Lib.site-packages.OpenGL.GLES1.OES',
              'venv.Lib.site-packages.OpenGL.GLES1.QCOM', 'venv.Lib.site-packages.OpenGL.GLES1.APPLE',
              'venv.Lib.site-packages.OpenGL.GLES1.VERSION', 'venv.Lib.site-packages.OpenGL.GLES2',
              'venv.Lib.site-packages.OpenGL.GLES2.FJ', 'venv.Lib.site-packages.OpenGL.GLES2.NV',
              'venv.Lib.site-packages.OpenGL.GLES2.AMD', 'venv.Lib.site-packages.OpenGL.GLES2.ARM',
              'venv.Lib.site-packages.OpenGL.GLES2.DMP', 'venv.Lib.site-packages.OpenGL.GLES2.EXT',
              'venv.Lib.site-packages.OpenGL.GLES2.IMG', 'venv.Lib.site-packages.OpenGL.GLES2.KHR',
              'venv.Lib.site-packages.OpenGL.GLES2.OES', 'venv.Lib.site-packages.OpenGL.GLES2.VIV',
              'venv.Lib.site-packages.OpenGL.GLES2.QCOM', 'venv.Lib.site-packages.OpenGL.GLES2.ANGLE',
              'venv.Lib.site-packages.OpenGL.GLES2.APPLE', 'venv.Lib.site-packages.OpenGL.GLES2.INTEL',
              'venv.Lib.site-packages.OpenGL.GLES2.VERSION', 'venv.Lib.site-packages.OpenGL.GLES3',
              'venv.Lib.site-packages.OpenGL.GLES3.VERSION', 'venv.Lib.site-packages.OpenGL.arrays',
              'venv.Lib.site-packages.OpenGL.osmesa', 'venv.Lib.site-packages.OpenGL.platform',
              'venv.Lib.site-packages.visvis', 'venv.Lib.site-packages.visvis.core',
              'venv.Lib.site-packages.visvis.text', 'venv.Lib.site-packages.visvis.text.freetype',
              'venv.Lib.site-packages.visvis.vvio', 'venv.Lib.site-packages.visvis.utils',
              'venv.Lib.site-packages.visvis.utils.iso', 'venv.Lib.site-packages.visvis.utils.ssdf',
              'venv.Lib.site-packages.visvis.vvmovie', 'venv.Lib.site-packages.visvis.backends',
              'venv.Lib.site-packages.visvis.wibjects', 'venv.Lib.site-packages.visvis.wobjects',
              'venv.Lib.site-packages.visvis.functions', 'venv.Lib.site-packages.visvis.processing',
              'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli',
              'venv.Lib.site-packages.confapp', 'venv.Lib.site-packages.example', 'venv.Lib.site-packages.pyforms',
              'venv.Lib.site-packages.urllib3', 'venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.urllib3.contrib', 'venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.urllib3.packages', 'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.orquestra', 'venv.Lib.site-packages.matplotlib',
              'venv.Lib.site-packages.matplotlib.tri', 'venv.Lib.site-packages.matplotlib.axes',
              'venv.Lib.site-packages.matplotlib.cbook', 'venv.Lib.site-packages.matplotlib.style',
              'venv.Lib.site-packages.matplotlib.compat', 'venv.Lib.site-packages.matplotlib.testing',
              'venv.Lib.site-packages.matplotlib.testing.jpl_units', 'venv.Lib.site-packages.matplotlib.backends',
              'venv.Lib.site-packages.matplotlib.backends.qt_editor', 'venv.Lib.site-packages.matplotlib.sphinxext',
              'venv.Lib.site-packages.matplotlib.projections', 'venv.Lib.site-packages.pyreadline',
              'venv.Lib.site-packages.pyreadline.test', 'venv.Lib.site-packages.pyreadline.modes',
              'venv.Lib.site-packages.pyreadline.console', 'venv.Lib.site-packages.pyreadline.keysyms',
              'venv.Lib.site-packages.pyreadline.clipboard', 'venv.Lib.site-packages.pyreadline.lineeditor',
              'venv.Lib.site-packages.setuptools', 'venv.Lib.site-packages.setuptools.extern',
              'venv.Lib.site-packages.setuptools._vendor', 'venv.Lib.site-packages.setuptools._vendor.packaging',
              'venv.Lib.site-packages.setuptools.command', 'venv.Lib.site-packages.simplejson',
              'venv.Lib.site-packages.simplejson.tests', 'venv.Lib.site-packages.pyforms_gui',
              'venv.Lib.site-packages.pyforms_gui.utils', 'venv.Lib.site-packages.pyforms_gui.dialogs',
              'venv.Lib.site-packages.pyforms_gui.controls',
              'venv.Lib.site-packages.pyforms_gui.controls.control_player',
              'venv.Lib.site-packages.pyforms_gui.controls.control_events_graph',
              'venv.Lib.site-packages.pyforms_gui.controls.control_event_timeline',
              'venv.Lib.site-packages.pyforms_web', 'venv.Lib.site-packages.pyforms_web.web',
              'venv.Lib.site-packages.pyforms_web.web.management',
              'venv.Lib.site-packages.pyforms_web.web.management.commands',
              'venv.Lib.site-packages.pyforms_web.web.middleware', 'venv.Lib.site-packages.pyforms_web.widgets',
              'venv.Lib.site-packages.pyforms_web.widgets.django', 'venv.Lib.site-packages.pyforms_web.controls',
              'venv.Lib.site-packages.mpl_toolkits.mplot3d', 'venv.Lib.site-packages.mpl_toolkits.axes_grid',
              'venv.Lib.site-packages.mpl_toolkits.axes_grid1', 'venv.Lib.site-packages.mpl_toolkits.axisartist',
              'venv.Lib.site-packages.pkg_resources', 'venv.Lib.site-packages.pkg_resources.extern',
              'venv.Lib.site-packages.pkg_resources._vendor', 'venv.Lib.site-packages.pkg_resources._vendor.packaging',
              'venv.Lib.site-packages.pyforms_terminal', 'venv.Lib.site-packages.pyforms_terminal.utils',
              'venv.Lib.site-packages.pyforms_terminal.controls'],
    url='',
    license='GPL v3',
    author='nautilus',
    author_email='',
    description=''
)
